# Generated by Django 4.1 on 2023-03-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profession',
            field=models.TextField(blank=True, default='Assistant Professor', null=True),
        ),
    ]
